---
title: "Data Wrangling in R"
author: "Pramod Duvvuri"
date: "3/30/2019"
output: pdf_document
---

## Tibble

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=9, fig.height=5)
```

```{r}
library(tidyverse)
library(nycflights13)
```

```{r}
as_tibble(iris) # coerce into a tibble
```

```{r}
tibble(x = 1:5,
       y = 1,
       z = x ^ 2 + 2 * y)
```

```{r}
flights %>% print(n = 10) # width = Inf can be used to print more columns
#flights %>% View()
```

```{r}
df <- tibble(x = runif(5),
             y = rnorm(5))
```

```{r}
df$x
df[["x"]]
df[[1]]
```

```{r}
class(mtcars)
class(df)
```

## readr

The read_csv() in readr package in faster than the base read.csv() by over (~10x). Also data.table::fread() can read data in at blazing speeds.

1. read_csv()
2. read_csv2()
3. read_tsv()
4. read_fwf()
5. read_log()
6. read_delim()

### Parsing Functions

1. parse_logical()
2. parse_integer()
3. parse_date()

## tidyr

1. gather()
2. spread()

```{r}
table4a # untidy data
```

