---
title: "Exploratory Data Analysis"
subtitle: "Introduction to EDA"
author: "Pramod Duvvuri"
date: "3/11/2019"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=9, fig.height=5) 
```

# Univariate Data

## Learning Grammar of Graphics (ggplot2)

```{r}
# Load installed packages
library('lattice')
library('ggplot2')
```

```{r}
ggplot(singer, aes(x = height))
```

```{r}
# ECDF in ggplot2
ggplot(singer, aes(x = height)) + stat_ecdf()
```

### Basic Plots

```{r}
# Alternate way to get ECDF
singer_gg <- ggplot(singer, aes(x = height))
singer_gg + stat_ecdf()
```

```{r}
# Add Labels
singer_gg + stat_ecdf() + ggtitle('ECDF')
```

```{r}
# Histogram
#ggplot(singer, aes(x= height)) + geom_histogram()
ggplot(singer, aes(x= height)) + geom_histogram(binwidth = 1)
```

```{r}
# Density Plot
ggplot(singer, aes(x= height)) + 
  geom_density()

ggplot(singer, aes(x= height)) + 
  geom_density(adjust = 0.5)
```

```{r}
# Boxplot 
ggplot(singer, aes(x= "Height", y = height)) + geom_boxplot()
```

```{r}
# Multiple Boxplots
ggplot(singer, aes(x = voice.part, y = height)) + geom_boxplot()
```

```{r}
# QQ-Plot using a Normal Distribution
ggplot(singer, aes(sample = height)) + stat_qq()
```

```{r}
# QQ-Plot using a Uniform Distribution
ggplot(singer, aes(sample = height)) + 
  stat_qq(distribution = qunif)
```

```{r}
# Facet
ggplot(singer,aes(sample = height)) + 
  stat_qq(distribution = qunif) +
  facet_grid(~voice.part)
```

```{r}
# The plot above looks cramped, so let us try a grid with columns
ggplot(singer, aes(sample = height)) + 
  stat_qq(distribution = qunif) +
  facet_wrap(~voice.part, ncol = 2)
```

```{r}
# QQ-Plot using Base R function qqplot()
Tenor1 = singer$height[singer$voice.part == "Tenor 1"]
Bass2 = singer$height[singer$voice.part == "Bass 2"]
qqplot(Tenor1, Bass2)
abline(0, 1)
```

```{r}
# Using ggplot
#library(tibble)
#qq_df <- as.tibble(qqplot(Tenor1, Bass2, plot.it = FALSE))
qq_df <- as.data.frame(qqplot(Tenor1, Bass2, plot.it = FALSE))
ggplot(data = qq_df, mapping = 
         aes(x = x, y = y)) + 
  geom_point() + 
  geom_abline()
```

```{r}
## Tukey-Mean difference Plot
ggplot(data = qq_df, mapping = aes(x = (x + y)/2, y = y - x)) + 
  geom_point() + 
  geom_abline(slope = 0) + ggtitle("Tukey Mean-Difference Plot")
```

```{r}
singer_means <- aggregate(height ~ voice.part, FUN = mean, data = singer)
```

```{r}
ggplot(singer_means, aes(x = voice.part, y = height)) + geom_point() + coord_flip()
```

```{r}
# Fitting a linear model
singer.lm <- lm(height ~ voice.part, data = singer)
```

```{r}
# Extracting residual values
singer.res <- data.frame(voice.part = singer$voice.part, residual = residuals(singer.lm))
```

```{r}
# Observing Residuals using boxplots
ggplot(singer.res, aes(x = voice.part, y = residual)) + geom_boxplot() + coord_flip()
```

```{r}
# Checking normality of residuals
ggplot(singer.res, aes(sample = residual)) + 
  stat_qq() + 
  facet_wrap(~voice.part, ncol = 2)
```

```{r}
# QQ Plot for Normality
ggplot(singer.res, aes(sample = residual)) + 
  stat_qq()
```

```{r}
# QQ Plot for Normality and adding slope and intercept
ggplot(singer.res, aes(sample = residual)) + 
  stat_qq() + geom_abline(intercept = 0,
slope = summary(singer.lm)$sigma)
```

```{r}
# Prepare Data
singer.fitted <- sort(fitted.values(singer.lm)) - mean(fitted.values(singer.lm))
singer.residuals <- sort(residuals(singer.lm))
n = length(singer.residuals)
f.value = (0.5:(n - 0.5))/n
singer.fit = data.frame(f.value, Fitted = singer.fitted, Residuals = singer.residuals)
```

```{r}
library(tidyr)
singer.fit.long = singer.fit %>% gather(type, value, Fitted:Residuals)
```

```{r}
# Residual-Fit spread plot
ggplot(singer.fit.long, aes(x = f.value, y = value)) + 
  geom_point() + 
  facet_wrap(~type)
```

```{r}
# Using stat_qq() to calculate f-values
ggplot(singer.fit.long, aes(sample = value)) + 
  stat_qq(distribution = "qunif") + 
  facet_grid(~type)
```

```{r}
# Using R-Squared
round(var(singer.fitted)/var(singer$height),3)
```

```{r}
url <- "https://github.com/hadley/tidy-data/raw/master/data/billboard.csv"
billboard.raw <- read.csv(url, stringsAsFactors = FALSE)
```

```{r}
# Creating a Tibble
library(dplyr)
billboard <- tbl_df(billboard.raw)
billboard
```

```{r}
# Calculating time-length of each song
billboard.time <- strsplit(billboard$time, ":")
billboard.time <- matrix(unlist(billboard.time), byrow = T, ncol = 2)
billboard.mins <- as.numeric(billboard.time[, 1])
billboard.secs <- as.numeric(billboard.time[, 2])
billboard.time <- billboard.mins * 60 + billboard.secs
billboard$time <- billboard.time/60
```

```{r}
billboard.long <- billboard %>% 
  gather(week, rank, x1st.week:x76th.week, na.rm = TRUE)
billboard.long
```

```{r}
ggplot(billboard, aes(x = time)) + 
  geom_histogram(breaks = seq(2.5, 8, 0.25))
```

```{r}
# Finding mean song length
time.means = aggregate(time ~ rank, FUN = mean, data = billboard.long)
```

```{r}
# Plotting mean song lenghts
ggplot(time.means, aes(x = rank, y = time)) + geom_line()
```

### Transformations

#### Log Transformation


```{r}
# Load data from workspace
load("./data/lattice.RData")
```

```{r}
summary(fusion.time)
```

```{r}
# Plot without data transformation
time = fusion.time$time
nv.vv = fusion.time$nv.vv
NV.times = sort(time[nv.vv == "NV"])
VV.times = sort(time[nv.vv == "VV"])
NV.VV.qq = as.data.frame(qqplot(NV.times, VV.times, plot.it = FALSE))

ggplot(NV.VV.qq, aes(x, y)) + geom_point() + geom_abline()
```

```{r}
# Using a log transformation
NV.times.log = sort(log2(time[nv.vv == "NV"]))
VV.times.log = sort(log2(time[nv.vv == "VV"]))
NV.VV.qq.log = as.data.frame(qqplot(NV.times.log, VV.times.log, plot.it = FALSE))

ggplot(NV.VV.qq.log, aes(x, y)) + geom_point() + geom_abline()
```

```{r}
# Tukey Mean-Difference Plot
ggplot(NV.VV.qq.log, aes((x + y)/2, y - x)) + geom_point()
```

#### Power Transformation


```{r}
n.VV = length(VV.times)
power = rep(seq(-1, 1, 0.25), each = n.VV)
VV.time = c(VV.times^-1, VV.times^-0.75, 
            VV.times^-0.5, VV.times^-0.25, 
            log(VV.times), VV.times^0.25, 
            VV.times^0.5, VV.times^0.75, VV.times)

ggplot(data.frame(power, VV.time), aes(sample = VV.time)) + 
  stat_qq() + facet_wrap(~power, scales = "free")
```

```{r}
summary(food.web)
```

```{r}
ggplot(food.web, aes(sample = mean.length)) + 
  stat_qq(distribution = qunif) + facet_grid(~dimension)
```

```{r}
web.length = food.web$mean.length
dimension = food.web$dimension
n = nrow(food.web)
median.3 = median(web.length[dimension == "Three"])
median.2 = median(web.length[dimension == "Two"])
median.mixed = median(web.length[dimension == "Mixed"])
group.median = rep(NA, n)
group.median[dimension == "Three"] = median.3
group.median[dimension == "Two"] = median.2
group.median[dimension == "Mixed"] = median.mixed
jittered.medians = group.median + runif(n, -0.1, 0.1)
root.abs.res = sqrt(abs(web.length - group.median))
food.web.sl = data.frame(jittered.medians, root.abs.res, dimension)
ggplot(food.web.sl, aes(jittered.medians, root.abs.res, col = dimension)) +
geom_point()
```

```{r}
# Using log transformation

log.web.length = log2(food.web$mean.length)
median.3.log = median(log.web.length[dimension == "Three"])
median.2.log = median(log.web.length[dimension == "Two"])
median.mixed.log = median(log.web.length[dimension == "Mixed"])
group.median.log = rep(NA, n)
group.median.log[dimension == "Three"] = median.3.log
group.median.log[dimension == "Two"] = median.2.log
group.median.log[dimension == "Mixed"] = median.mixed.log
jittered.medians.log = group.median.log + runif(n, -0.05, 0.05)
root.abs.res.log = sqrt(abs(log.web.length - group.median.log))
food.web.log.sl = data.frame(jittered.medians.log, root.abs.res.log, dimension)
ggplot(food.web.log.sl, aes(jittered.medians.log, root.abs.res.log, col = dimension)) +
geom_point()
```

```{r}
ggplot(food.web, aes(sample = log(mean.length))) + 
  stat_qq() +
  facet_wrap(~dimension)
```

```{r}
# Using Inverse Transformation
inv.web.length = 1/food.web$mean.length
median.3.inv = median(inv.web.length[dimension == "Three"])
median.2.inv = median(inv.web.length[dimension == "Two"])
median.mixed.inv = median(inv.web.length[dimension == "Mixed"])
group.median.inv = rep(NA, n)
group.median.inv[dimension == "Three"] = median.3.inv
group.median.inv[dimension == "Two"] = median.2.inv
group.median.inv[dimension == "Mixed"] = median.mixed.inv
jittered.medians.inv = group.median.inv + runif(n, -0.01, 0.01)
root.abs.res.inv = sqrt(abs(inv.web.length - group.median.inv))
food.web.inv.sl = data.frame(jittered.medians.inv, root.abs.res.inv, dimension)
ggplot(food.web.inv.sl, aes(jittered.medians.inv, root.abs.res.inv, col = dimension)) +
geom_point()
```

```{r}
# Calculate Mean
aggregate(root.abs.res.inv ~ dimension, FUN = mean)
```

```{r}
# Normality Check
ggplot(food.web, aes(sample = 1/mean.length)) + stat_qq() + facet_wrap(~dimension)
```

```{r}
food.web.lm = lm(inv.web.length ~ dimension)
food.web.res = residuals(food.web.lm)
res.qq.3 = qqplot(food.web.res, food.web.res[dimension == "Three"], plot.it = FALSE)
res.qq.2 = qqplot(food.web.res, food.web.res[dimension == "Two"], plot.it = FALSE)
res.qq.mixed = qqplot(food.web.res, food.web.res[dimension == "Mixed"], plot.it = FALSE)
food.web.res.qq = data.frame(pooled = c(res.qq.3$x, res.qq.2$x, res.qq.mixed$x),
residual = c(res.qq.3$y, res.qq.2$y, res.qq.mixed$y), dimension = c(rep("Three",
length(res.qq.3$x)), rep("Two", length(res.qq.2$x)), rep("Mixed", length(res.qq.mixed$x))))
ggplot(food.web.res.qq, aes(pooled, residual)) + geom_point() + geom_abline() +
facet_wrap(~dimension)
```

```{r}
# Residual Fitted Spread Plot
food.web.fitted = sort(fitted.values(food.web.lm)) - mean(fitted.values(food.web.lm))
n = length(inv.web.length)
f.value = (0.5:(n - 0.5))/n
food.web.fit = data.frame(f.value, Fitted = food.web.fitted, Residuals = sort(food.web.res))
library(tidyr)
food.web.fit.long = food.web.fit %>% gather(type, value, Fitted:Residuals)
ggplot(food.web.fit.long, aes(x = f.value, y = value)) + geom_point() + facet_wrap(~type)
```

