---
title: "Reddit Data Analysis"
author: "Pramod Duvvuri"
date: "4/2/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=9, fig.height=5) 
```

```{r}
# Reading Data
reddit_data <- read.csv('./reddit.csv')
head(reddit_data)
```

```{r}
table(reddit_data$employment.status)
#summary(reddit_data)
```

```{r}
levels(reddit_data$age.range)
```

```{r}
# Basic Plot of unordered factors
library(ggplot2)
qplot(data = reddit_data, x = age.range)
```

```{r}
qplot(data = reddit_data, x = income.range)
```

```{r}
# Creating ordered variables for better plots
reddit_data$age.range <- ordered(reddit_data$age.range,
                             levels = c("Under 18","18-24" ,
                                        "25-34","35-44","45-54",
                                        "55-64","65 or Above" ))
```

```{r}
qplot(data = reddit_data, x = age.range)
```

```{r}
levels(reddit_data$income.range)
```

```{r}
# Creating ordered variables for better plots
reddit_data$income.range <- ordered(reddit_data$income.range,
                             levels = c("Under $20,000","$20,000 - $29,999",
                                        "$30,000 - $39,999","$40,000 - $49,999",
                                        "$50,000 - $69,999","$70,000 - $99,999",
                                        "$100,000 - $149,999","$150,000 or more"))
qplot(data = reddit_data, x = income.range) + coord_flip() 
```

